---
driver:
  name: docker

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      privision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - yum install -y net-tools
        - systemctl enable sshd.service
  - name: ubuntu-18.04
    driver_config:
      run_command: /sbin/init
      privileged: true
      privision_command:
        - systemctl enable ssh.service

suites:
  - name: default
    run_list:
      - recipe[test-driven-redis::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
