---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos
    driver_config:
      image: amaltson/docker-redis-req-centos
      require_chef_omnibus: false

suites:
  - name: default
    run_list:
      - recipe[test-driven-redis::default]
    attributes:
