---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos
    driver_config:
      image: centos:centos6.6

suites:
  - name: default
    run_list:
      - recipe[test-driven-redis::default]
    attributes:
